application: ksrwaitr
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: view/css

- url: /fonts
  static_dir: view/fonts

- url: /img
  static_dir: view/img

- url: /js
  static_dir: view/js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest